sudo: false
language: objective-c
cache: cocoapods
xcode_workspace: LocationManager/LocationManager.xcworkspace
xcode_scheme: LocationManagerExample
xcode_sdk: iphonesimulator
podfile: LocationManager/Podfile

before_install:
  - gem install cocoapods --no-ri --no-rdoc
  - gem install slather --no-ri --no-rdoc

after_success: slather
